### ISSUE TITLE
Import, build and run instructions..

### ISSUE THREAD

**Issue by Mancutd** [maxbbraun/mirror#11]
Could someone offer instructions on how to "import, build and run the apk" please? 

The instructions seem simple enough but I couldn't get it to work. 

I'm sorry if this is a waste of time for some of you, I'm just very confused.

**Comment by maxbbraun** [comment]
Here's a step-by-step guide for pulling a project from GitHub into Android Studio: https://www.youtube.com/watch?v=E0MjorpDWxc
