### ISSUE TITLE
Can't Get weather to show up, even with valid key.

### ISSUE THREAD

**Issue by carsonbroom** [maxbbraun/mirror#16]
Can't get weather to show up, even with valid key.

**Comment by FlavourDaveMasterDDissle-theDtotheissle** [comment]
The forecast-API hast changed and mirror-project probably uses deprecated one. (http://us5.campaign-archive1.com/?u=367cd59eb4383bef7a3d6e48a&id=d49328d2b2&e=4d83805bb5)

**Comment by carsonbroom** [comment]
Thanks! Is this something I need to change myself, or is it something that
you will put in as an update on GitHub?

**Comment by maxbbraun** [comment]
Should be fixed by https://github.com/maxbbraun/mirror/commit/8d28baecf232ec2fa059d45953052ecb9ee4615e.

**Comment by carsonbroom** [comment]
Do you have to have an internet connection to be able to show the weather?
