### ISSUE TITLE
Temperature wrong in compact mode

### ISSUE THREAD

**Issue by Marko-Laaksonen** [maxbbraun/mirror#18]
Hello
Temperature is ok in activity_home view but in activity_compact it is 31C degrees too high. Is there a simple way to make  it correct? Another less important thing is that weather summarys language is always english. Is there a way to change it? My Androids language is Finnish so the date is in Finnish and the summary in English now.

BTW Thanks fot the app! It made me to use Android studio and modify your app quite a bit!

**Comment by brandonmowat** [comment]
Im fairly certain the weather summary is being served by forecast.io (now Dark Sky API). So you'll probably need to translate it yourself, unless dark sky let's you se the language.

**Comment by Marko-Laaksonen** [comment]
Thanks for the answer. Thats just what I thought. And the temperature seems to be wrong becouse there is no farenheit to celsius conversation in CompactHomeActivity.java

**Comment by brandonmowat** [comment]
Correct, but the API endpoint can be changed. I believe dark sky defaults to F for temperature, but you can find an endpoint for celcius temp.

**Comment by brandonmowat** [comment]
Can we close this issue? @Marko-Laaksonen

**Comment by Marko-Laaksonen** [comment]
Yes. I simply copy/paste code for weather from activity_home to activity_compact to get the F to C work.
