### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by tempdj** [maxbbraun/mirror#26]
Hi
Currently struggling to get the weather part working so any tips would be greatly appreciated. Maybe some examples or idea on how to get this working.
I have entered under keys XML
dark_sky_api_key">https://api.darksky.net/forecast/[my darksky key]/[longitude],[latitude]</string 
Longitude and latitude are filled in on my version.
Is there anything else I have to do or I am missing something somewhere.
Thanks

**Comment by parsons-owen** [comment]
Okay. So the API once you've got the API key from dark sky. Don't use that link it should just be a long string of numbers and letters. For example mine says 

<String name="dark_sky_api_key">here there's loads of numbers and letters</string>

**Comment by parsons-owen** [comment]
And if you want it in celcius i can help you do that if you like

**Comment by parsons-owen** [comment]
Oh and to find it go to darksky.net/dev/account and it will say your secret key just copy and paste that

**Comment by tempdj** [comment]
Cool. Will have a play tomorrow.

**Comment by guicrepin** [comment]
I'm only getting the 0 or 1 value for precipitation, no percentages. I can't seem to find what's happening, would you have an idea?
![image](https://user-images.githubusercontent.com/32506828/47500131-37d68380-d862-11e8-8c9c-d81b790e4ab5.png)
