### ISSUE TITLE
No tutorial! 😉

### ISSUE THREAD

**Issue by brandonmowat** [maxbbraun/mirror#3]
You should have a tutorial of how to build it! At least a list of parts and where to buy them.

**Comment by mattyams** [comment]
https://medium.com/@maxbraun/my-bathroom-mirror-is-smarter-than-yours-94b21c6671ba#.4exmyxt0w

**Comment by brandonmowat** [comment]
Yes, but it still isn't posted... Correct?

**Comment by BrendonKoz** [comment]
The list of parts are now just hyperlinked websites in the paragraph describing the parts used.

**Comment by tj000b** [comment]
I know this is a bit of topic but;
why do you use the controller from te fire-tv to the 40pin on the monitor instead of just using the fire-tv directly in the HDMI input on the monitor?
