### ISSUE TITLE
Amazon Fire icons 

### ISSUE THREAD

**Issue by mrmichaelfowler** [maxbbraun/mirror#5]
Is there a way for me to remove the default Amazon Fire Tablet icons? 

I installed this .apk on the table however now you can see a duplication of the time and you see a battery icon and navigation icons at the base on the table. 

Do you know of a way that I can remove these icons? They are disturbing my zen mirror :)

**Comment by mrmichaelfowler** [comment]
Found how to hide the navigation bar:
http://developer.android.com/training/system-ui/navigation.html

Just not sure on how we remove the icons (battery, time, etc) from the Adored tablet.

**Comment by mrmichaelfowler** [comment]
I believe immersive mode should allow me to solve both of my requests, 
http://developer.android.com/training/system-ui/immersive.html

Is this something I need to do from my end or something you could build into this apk? Sorry I am a newb to this :)

**Comment by kryptics** [comment]
Hey Michael, I never seen Max answer any of these questions, so we are kinda on our own :( but i'm glad to see you figure some stuff out :)

**Comment by maxbbraun** [comment]
Should be fixed by https://github.com/maxbbraun/mirror/commit/cf8472de1dac43dbf73ecc6df6eb3dc6ab0e9bfc.
